name: DavidGiesbrecht
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8670951654203236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f2f1'
    - '#101312'
    - '#696553'
    - '#a5ae9c'
    - '#393629'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
