name: DavidGiesbrecht
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79491
title: Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1668763-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f2f1'
    - '#101312'
    - '#696553'
    - '#a5ae9c'
    - '#393629'
  brandStrength: 0
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
