name: DavidGiesbrecht
favicon: null
layout_spectrum: 0.21353903110139072
typography_spectrum: 0.8670951654203236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f2f1'
    - '#101312'
    - '#696553'
    - '#a5ae9c'
    - '#393629'
  brandStrength: 0.1875
  lightness: 0.6630001945886761
  saturation: 0.9591072814073414
  rhythmicContrast: 0.9369339856784791
purpose: []
