name: DavidGiesbrecht
favicon: null
layout_spectrum: 0.75241
typography_spectrum: 0.79491
title: David Giesbrecht - Still Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1668763-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbf3da'
    - '#cfbbb7'
    - '#5d5474'
    - '#0b64ba'
  brandStrength: 0
  lightness: 0
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
